package com.nplus.bookmanager.service

import com.nplus.bookmanager.util.ProcessRunner
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import java.io.File
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

class BookHealthService(
    private val booksDir: File,
    private val portalDir: File,
    private val newBooksDir: File? = null,
) {
    val healthFile: File get() = File(portalDir, "src/data/health.json")

    companion object {
        const val NEAR_EMPTY_DENSITY = 250
        const val THIN_CHARS = 8_000
        const val WATCH_CHARS = 15_000

        private val ISO_DATE = Regex("""\d{4}-\d{2}-\d{2}""")

        fun bodyChars(file: File): Int {
            var fence = 0
            var total = 0
            file.forEachLine { line ->
                if (line.trim() == "---") {
                    fence++
                } else if (fence >= 2) {
                    total += line.length + 1
                }
            }
            return total
        }

        fun isDraft(file: File): Boolean {
            var fence = 0
            var draft = false
            file.forEachLine { line ->
                if (line.trim() == "---") {
                    fence++
                } else if (fence == 1 && line.trim().replace(" ", "") == "draft:true") {
                    draft = true
                }
            }
            return draft
        }
    }

    data class Book(
        val slug: String,
        val top: String,
        val sub: String,
        val leaf: String,
        val chars: Int,
        val pages: Int,
        val lastWritten: String? = null,
    ) {
        val density: Int get() = if (pages == 0) 0 else (chars + pages / 2) / pages

        val tier: String
            get() =
                when {
                    density < NEAR_EMPTY_DENSITY -> "near-empty"
                    chars < THIN_CHARS -> "thin"
                    chars < WATCH_CHARS -> "watch"
                    else -> "ok"
                }
    }

    fun scan(): List<Book> {
        if (!booksDir.isDirectory) return emptyList()
        val books = mutableListOf<Book>()
        for (top in booksDir.listDirs()) {
            for (sub in top.listDirs()) {
                for (leaf in sub.listDirs()) {
                    for (repo in leaf.listDirs()) {
                        measure(repo, top.name, sub.name, leaf.name)?.let { books += it }
                    }
                }
            }
        }
        newBooksDir?.takeIf { it.isDirectory }?.let { dir ->
            for (repo in dir.listDirs()) {
                measure(repo, top = "", sub = "", leaf = "")?.let { books += it }
            }
        }
        return books.sortedBy { it.slug }
    }

    private fun measure(
        repo: File,
        top: String,
        sub: String,
        leaf: String,
    ): Book? {
        val docs = File(repo, "site/content/docs")
        if (!docs.isDirectory) return null
        val pages =
            docs
                .walkTopDown()
                .filter { it.isFile && it.extension == "md" && !isDraft(it) }
                .toList()
        if (pages.isEmpty()) return null
        return Book(
            slug = repo.name,
            top = top,
            sub = sub,
            leaf = leaf,
            chars = pages.sumOf { bodyChars(it) },
            pages = pages.size,
            lastWritten = lastWritten(repo),
        )
    }

    private fun File.listDirs(): List<File> =
        listFiles()?.filter { it.isDirectory && !it.name.startsWith(".") }?.sortedBy { it.name } ?: emptyList()

    private fun lastWritten(repoDir: File): String? {
        val result =
            ProcessRunner.execute(
                "git log -1 --format=%aI -- site/content/docs",
                workingDir = repoDir,
                timeoutSeconds = 15,
            )
        if (!result.success) return null
        return result.stdout
            .trim()
            .take(10)
            .takeIf { it.matches(ISO_DATE) }
    }

    fun save(books: List<Book>) {
        val root =
            buildJsonObject {
                put(
                    "\$comment",
                    "DERIVED — generated by hugo-book-manager `./gradlew refreshBookHealth`. Do not edit by hand.",
                )
                put("generatedAt", OffsetDateTime.now(ZoneOffset.UTC).format(DateTimeFormatter.ISO_OFFSET_DATE_TIME))
                put(
                    "thresholds",
                    buildJsonObject {
                        put("nearEmptyDensity", NEAR_EMPTY_DENSITY)
                        put("thinChars", THIN_CHARS)
                        put("watchChars", WATCH_CHARS)
                    },
                )
                put("books", buildJsonArray { for (b in books) add(bookJson(b)) })
            }
        healthFile.parentFile?.mkdirs()
        healthFile.writeText(prettyJson.encodeToString(JsonObject.serializer(), root) + "\n")
    }

    private fun bookJson(b: Book): JsonObject =
        buildJsonObject {
            put("slug", b.slug)
            put("top", b.top)
            put("sub", b.sub)
            put("leaf", b.leaf)
            put("chars", b.chars)
            put("pages", b.pages)
            put("density", b.density)
            put("tier", b.tier)
            b.lastWritten?.let { put("lastWritten", it) }
        }

    private val prettyJson =
        Json {
            prettyPrint = true
            prettyPrintIndent = "  "
        }
}
