package com.nplus.bookmanager.service

import com.nplus.bookmanager.model.DocsStructure
import java.io.File

/**
 * Service for creating and managing Hugo docs folder structure.
 *
 * Creates the docs directory structure based on AI-generated DocsStructure,
 * including section folders and _index.md files.
 */
class DocsStructureService {
    /**
     * Create docs folder structure in the given repo directory.
     *
     * @param repoDir The root directory of the Hugo Book repository
     * @param structure The DocsStructure generated by AI
     * @param clearExisting If true, remove existing folders before creating new ones
     * @return Number of items created
     */
    fun createDocsStructure(
        repoDir: File,
        structure: DocsStructure,
        clearExisting: Boolean = true,
    ): Int {
        val docsDir = File(repoDir, "site/content/docs")

        if (!docsDir.exists()) {
            docsDir.mkdirs()
        }

        // Remove existing placeholder folders (keep only _index.md in docs root)
        if (clearExisting) {
            docsDir.listFiles()?.filter { it.isDirectory }?.forEach { it.deleteRecursively() }
        }

        var createdCount = 0

        for (section in structure.sections) {
            if (section.chapters.isEmpty()) {
                // Flat chapter (no sub-chapters)
                createChapterFolder(docsDir, section.folderName, section.title, section.weight)
                createdCount++
            } else {
                // Section with chapters
                val sectionDir = File(docsDir, section.folderName)
                sectionDir.mkdirs()

                // Create section _index.md
                createSectionIndex(sectionDir, section.title, section.weight)
                createdCount++

                // Create chapter folders
                for (chapter in section.chapters) {
                    createChapterFolder(sectionDir, chapter.folderName, chapter.title, chapter.weight)
                    createdCount++
                }
            }
        }

        return createdCount
    }

    /**
     * Create a section _index.md file.
     */
    private fun createSectionIndex(
        sectionDir: File,
        title: String,
        weight: Int,
    ) {
        val indexFile = File(sectionDir, "_index.md")
        indexFile.writeText(
            """
            |---
            |title: "$title"
            |weight: $weight
            |bookCollapseSection: true
            |---
            """.trimMargin(),
        )
    }

    /**
     * Create a chapter folder with _index.md file.
     */
    private fun createChapterFolder(
        parentDir: File,
        folderName: String,
        title: String,
        weight: Int,
    ) {
        val chapterDir = File(parentDir, folderName)
        chapterDir.mkdirs()

        val indexFile = File(chapterDir, "_index.md")
        indexFile.writeText(
            """
            |---
            |title: "$title"
            |weight: $weight
            |---
            """.trimMargin(),
        )
    }

    /**
     * Print the docs structure to console.
     */
    fun printDocsStructure(structure: DocsStructure) {
        println("  Docs structure:")
        structure.sections.forEach { section ->
            if (section.chapters.isEmpty()) {
                println("    ${section.folderName}/ - ${section.title}")
            } else {
                println("    ${section.folderName}/ - ${section.title}")
                section.chapters.forEach { chapter ->
                    println("      ${chapter.folderName}/ - ${chapter.title}")
                }
            }
        }
    }
}
